# Generated by Django 5.2 on 2025-04-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('ID_movie', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name_movie', models.CharField(max_length=255)),
                ('Linkaddress_Poster', models.URLField(max_length=500)),
                ('Year_of_manufacture', models.IntegerField()),
                ('Country_of_origin', models.CharField(max_length=100)),
                ('Number_of_episodes', models.IntegerField()),
                ('categories', models.ManyToManyField(related_name='movies', to='category.category')),
            ],
        ),
    ]
