# Generated by Django 5.2 on 2025-05-04 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('ID_ep', models.BigAutoField(primary_key=True, serialize=False)),
                ('Linkaddress_ep', models.URLField(max_length=500)),
                ('Name_ep', models.CharField(max_length=255)),
                ('ID_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='movie.movie')),
            ],
        ),
    ]
